---
# Weather Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  labels:
    app: weather-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
      - name: weather-service
        image: weather-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
          name: http

---
# Weather Service ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: weather-service

---
# Packing Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packing-service
  labels:
    app: packing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packing-service
  template:
    metadata:
      labels:
        app: packing-service
    spec:
      containers:
      - name: packing-service
        image: packing-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
          name: http

---
# Packing Service ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: packing-service
  labels:
    app: packing-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: packing-service

---
# Agent Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agent
  labels:
    app: travel-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-agent
  template:
    metadata:
      labels:
        app: travel-agent
    spec:
      containers:
      - name: travel-agent
        image: travel-agent:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: api-key

---
# Agent NodePort Service (for external access)
apiVersion: v1
kind: Service
metadata:
  name: travel-agent
  labels:
    app: travel-agent
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: travel-agent

